=== Mistribe/SubTracker/backend/data/schemas/familiesSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "description": "The unique identifier for the family"
            },
            "owner_id": {
                "type": "string",
                "description": "The unique identifier of the user in IDP"
            },
            "name": {
                "type": "string",
                "description": "The name of the family"
            },
            "members": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "The unique identifier for the family's member"
                        },
                        "name": {
                            "type": "string",
                            "description": "The name of the family's member"
                        },
                        "user_id": {
                            "type": "string",
                            "description": "The unique identifier of the user in IDP"
                        },
                        "type": {
                            "type": "string",
                            "description": "The type of the member. Can be owner,adult or kid"
                        }
                    }
                }
            }
        }
    }
}

=== Mistribe/SubTracker/backend/data/families.json
[
    {
        "id": "d317369c-c6ec-4e04-9277-d7477a9635e9",
        "owner_id": "kp_4de08ac140e54e5081b192b48c1b660e",
        "name": "Tribe",
        "members": [
            {
                "id": "c40cf18e-1ca8-4646-866e-5252a5f7b02f",
                "name": "Maxime",
                "user_id": "kp_4de08ac140e54e5081b192b48c1b660e",
                "type": "owner"
            },
            {
                "id": "16e151e4-3e17-490d-9228-f275b1d1d833",
                "name": "In√®s",
                "type": "adult"
            },
            {
                "id": "341eea0d-752c-4b4a-9122-b0aff91c632f",
                "name": "Amos",
                "type": "kid"
            }
        ]
    }
]
